Repository MENDITTZO/DEBOOK_FrontEnd, pull requests merged in 2024-11, with the labels that each got.

#4 [setting] #2 프론트엔드 프로젝트 초기 세팅 파일 업로드
  MENDITTZO-Frontend/.gitignore
  MENDITTZO-Frontend/.vscode/extensions.json
  MENDITTZO-Frontend/README.md
  MENDITTZO-Frontend/index.html
  MENDITTZO-Frontend/jsconfig.json
  MENDITTZO-Frontend/package.json
  MENDITTZO-Frontend/public/favicon.ico
  MENDITTZO-Frontend/src/App.vue
  MENDITTZO-Frontend/src/assets/test.md
  MENDITTZO-Frontend/src/components/test.md
  MENDITTZO-Frontend/src/config/test.md
  MENDITTZO-Frontend/src/main.js
  MENDITTZO-Frontend/src/router/test.md
  MENDITTZO-Frontend/src/store/test.md
  MENDITTZO-Frontend/src/views/test.md
  MENDITTZO-Frontend/vite.config.js
Labels: ⚙ Setting

#7 Feat/navigation: #6 네비게이션바 스타일 구현
  MENDITTZO-Frontend/package-lock.json
  MENDITTZO-Frontend/src/App.vue
  MENDITTZO-Frontend/src/assets/image/logo.png
  MENDITTZO-Frontend/src/assets/image/profile.png
  MENDITTZO-Frontend/src/assets/image/search-icon.png
  MENDITTZO-Frontend/src/assets/image/sign-up.png
  MENDITTZO-Frontend/src/assets/test.md
  MENDITTZO-Frontend/src/components/NavigationBar.vue
  MENDITTZO-Frontend/src/components/test.md
  MENDITTZO-Frontend/src/main.js
Labels: 🎨 Style, ✨ Feat

#9 Feat/footer : #8 푸터 HTML/CSS 구현
  MENDITTZO-Frontend/src/App.vue
  MENDITTZO-Frontend/src/assets/image/github-mark.png
  MENDITTZO-Frontend/src/assets/image/logo_gray.png
  MENDITTZO-Frontend/src/components/Footer.vue
  MENDITTZO-Frontend/src/main.js
Labels: 🎨 Style, ✨ Feat

#12 Feat/style : #11 마이페이지 HTML/CSS 구현, 라우팅 파일 생성
  MENDITTZO-Frontend/.gitignore
  MENDITTZO-Frontend/package-lock.json
  MENDITTZO-Frontend/package.json
  MENDITTZO-Frontend/src/App.vue
  MENDITTZO-Frontend/src/assets/image/bookmark.png
  MENDITTZO-Frontend/src/assets/image/bookmark2.png
  MENDITTZO-Frontend/src/assets/image/delete.png
  MENDITTZO-Frontend/src/assets/image/empty-star.png
  MENDITTZO-Frontend/src/assets/image/modify.png
  MENDITTZO-Frontend/src/assets/image/star.png
  MENDITTZO-Frontend/src/components/Footer.vue
  MENDITTZO-Frontend/src/main.js
  MENDITTZO-Frontend/src/router/index.js
  MENDITTZO-Frontend/src/router/test.md
  MENDITTZO-Frontend/src/views/MyPage.vue
  MENDITTZO-Frontend/src/views/test.md
Labels: 🎨 Style, ✨ Feat

#14 Feat/booklist: #13 도서 목록 조회 페이지 구현 및 CSS 적용
  MENDITTZO-Frontend/package-lock.json
  MENDITTZO-Frontend/package.json
  MENDITTZO-Frontend/src/assets/image/first-page.png
  MENDITTZO-Frontend/src/assets/image/last-page.png
  MENDITTZO-Frontend/src/assets/image/next-page.png
  MENDITTZO-Frontend/src/assets/image/previous-page.png
  MENDITTZO-Frontend/src/components/BookListComponents.vue
  MENDITTZO-Frontend/src/components/BookListItem.vue
  MENDITTZO-Frontend/src/components/NavigationBar.vue
  MENDITTZO-Frontend/src/components/PagingBar.vue
  MENDITTZO-Frontend/src/router/index.js
  MENDITTZO-Frontend/src/views/BookListView.vue
Labels: ✨ Feat

#16 Feat/mainpage : #10 메인 페이지 기능 구현
  MENDITTZO-Frontend/package-lock.json
  MENDITTZO-Frontend/package.json
  MENDITTZO-Frontend/src/assets/image/ad1.png
  MENDITTZO-Frontend/src/assets/image/ad2.png
  MENDITTZO-Frontend/src/assets/image/ad3.png
  MENDITTZO-Frontend/src/components/NavigationBar.vue
  MENDITTZO-Frontend/src/main.js
  MENDITTZO-Frontend/src/router/index.js
  MENDITTZO-Frontend/src/views/BookListView.vue
  MENDITTZO-Frontend/src/views/MainPage.vue
Labels: 🎨 Style, ✨ Feat

#18 Feat/login/#5 로그인, 홈 화면 연동
  MENDITTZO-Frontend/package-lock.json
  MENDITTZO-Frontend/package.json
  MENDITTZO-Frontend/src/assets/image/google-logo.png
  MENDITTZO-Frontend/src/assets/image/info-icon.png
  MENDITTZO-Frontend/src/assets/image/kakao-logo.png
  MENDITTZO-Frontend/src/assets/image/naver-logo.png
  MENDITTZO-Frontend/src/assets/image/광고배너1.png
  MENDITTZO-Frontend/src/assets/image/광고배너2.png
  MENDITTZO-Frontend/src/assets/image/광고배너3.png
  MENDITTZO-Frontend/src/assets/image/북마크아이콘1.png
  MENDITTZO-Frontend/src/assets/image/북마크아이콘2.png
  MENDITTZO-Frontend/src/assets/image/책론을박로고1.png
  MENDITTZO-Frontend/src/assets/image/책론을박로고1_gray.png
  MENDITTZO-Frontend/src/components/NavigationBar.vue
  MENDITTZO-Frontend/src/components/common/ButtonLong.vue
  MENDITTZO-Frontend/src/main.js
  MENDITTZO-Frontend/src/router/router.js
  MENDITTZO-Frontend/src/store/auth.js
  MENDITTZO-Frontend/src/views/HomeView.vue
  MENDITTZO-Frontend/src/views/Login/LoginForm.vue
  MENDITTZO-Frontend/src/views/Login/LoginSuccessView.vue
  MENDITTZO-Frontend/src/views/MyPage.vue
Labels: ✨ Feat

#19 Feat/mypage : #17 마이페이지 기능 수정
  MENDITTZO-Frontend/src/store/test.md
  MENDITTZO-Frontend/src/views/Login/LoginForm.vue
  MENDITTZO-Frontend/src/views/MyPage.vue
Labels: 🎨 Style, ✨ Feat

#22 style: 탈퇴 모달 추가/api 요청에 액세스 토큰 포함하도록 설정
  MENDITTZO-Frontend/src/components/NavigationBar.vue
  MENDITTZO-Frontend/src/components/SignOutForm.vue
  MENDITTZO-Frontend/src/config/axios.js
  MENDITTZO-Frontend/src/main.js
  MENDITTZO-Frontend/src/store/auth.js
  MENDITTZO-Frontend/src/views/MyPage.vue
Labels: 🎨 Style, ✨ Feat

#23 Feat/booklist: #15 도서 상세페이지 구현
  MENDITTZO-Frontend/src/App.vue
  MENDITTZO-Frontend/src/assets/image/close-icon.png
  MENDITTZO-Frontend/src/assets/image/emergency.png
  MENDITTZO-Frontend/src/assets/image/filled-star.png
  MENDITTZO-Frontend/src/assets/image/open-icon.png
  MENDITTZO-Frontend/src/assets/image/review-close.png
  MENDITTZO-Frontend/src/assets/image/review-open.png
  MENDITTZO-Frontend/src/components/BookDetailComponent.vue
  MENDITTZO-Frontend/src/components/ReviewItem.vue
  MENDITTZO-Frontend/src/components/ReviewListComponent.vue
  MENDITTZO-Frontend/src/components/common/BigButton.vue
  MENDITTZO-Frontend/src/components/common/ConfirmModal.vue
  MENDITTZO-Frontend/src/components/common/DropDownMenu.vue
  MENDITTZO-Frontend/src/components/common/Footer.vue
  MENDITTZO-Frontend/src/components/common/NavigationBar.vue
  MENDITTZO-Frontend/src/components/common/PagingBar.vue
  MENDITTZO-Frontend/src/components/common/SmallButton.vue
  MENDITTZO-Frontend/src/router/index.js
  MENDITTZO-Frontend/src/router/router.js
  MENDITTZO-Frontend/src/views/BookDetailView.vue
  MENDITTZO-Frontend/src/views/BookListView.vue
  MENDITTZO-Frontend/src/views/BookReviewCreateView.vue
  MENDITTZO-Frontend/src/views/MainPage.vue
  MENDITTZO-Frontend/src/views/MyPage.vue
Labels: ✨ Feat

#32 Chore: #30 자잘한 코드 수정
  MENDITTZO-Frontend/src/components/ReviewItem.vue
  MENDITTZO-Frontend/src/components/SignOutForm.vue
  MENDITTZO-Frontend/src/router/router.js
  MENDITTZO-Frontend/src/views/BookDetailView.vue
  MENDITTZO-Frontend/src/views/BookListView.vue
  MENDITTZO-Frontend/src/views/BookReviewCreateView.vue
  MENDITTZO-Frontend/src/views/BookReviewEditView.vue
  MENDITTZO-Frontend/src/views/Login/LoginForm.vue
  MENDITTZO-Frontend/src/views/MyPage.vue
Labels: 💻 Chore

#33 chore: 폰트 설정, 간격 조정 등
  MENDITTZO-Frontend/src/assets/global.css
  MENDITTZO-Frontend/src/components/SignOutForm.vue
  MENDITTZO-Frontend/src/components/common/NavigationBar.vue
  MENDITTZO-Frontend/src/main.js
  MENDITTZO-Frontend/src/views/Login/LoginForm.vue
  MENDITTZO-Frontend/src/views/MyPage.vue
Labels: 💻 Chore

#36 feat/elasticsearch:#28 검색엔진 프론트 엔드 구현 및 검색결과 페이지 이동
  MENDITTZO-Frontend/src/components/common/NavigationBar.vue
Labels: ✨ Feat

#37 feat/elastic:#28 검색엔진 미리보기 바깥 클릭시 꺼지는 기능 구현
  MENDITTZO-Frontend/src/components/common/NavigationBar.vue
Labels: ✨ Feat

#38 Feat/recommend/#27
  MENDITTZO-Frontend/src/components/common/NavigationBar.vue
  MENDITTZO-Frontend/src/router/router.js
  MENDITTZO-Frontend/src/store/auth.js
  MENDITTZO-Frontend/src/views/BookRecommendView.vue
Labels: ✨ Feat

#39 Chore: #26 라우팅 등 일부 오류 수정
  MENDITTZO-Frontend/src/components/common/NavigationBar.vue
  MENDITTZO-Frontend/src/views/BookReviewCreateView.vue
  MENDITTZO-Frontend/src/views/BookReviewEditView.vue
  MENDITTZO-Frontend/src/views/MainPage.vue
  MENDITTZO-Frontend/src/views/MyPage.vue
Labels: 💻 Chore

#40 feat/chat 채팅방 뷰 구현
  MENDITTZO-Frontend/package-lock.json
  MENDITTZO-Frontend/package.json
  MENDITTZO-Frontend/src/components/common/NavigationBar.vue
  MENDITTZO-Frontend/src/router/router.js
  MENDITTZO-Frontend/src/views/ChatroomList.vue
  MENDITTZO-Frontend/src/views/ChatroomView.vue
Labels: 🎨 Style, ✨ Feat

#42 chore: #41 CSS 수정
  MENDITTZO-Frontend/src/components/common/NavigationBar.vue
  MENDITTZO-Frontend/src/components/common/TopButton.vue
Labels: 🎨 Style, 💻 Chore

#44 feat/chat: 책 정보 추가
  MENDITTZO-Frontend/src/views/ChatroomList.vue
  MENDITTZO-Frontend/src/views/ChatroomView.vue
Labels: ✨ Feat

#45 Chore: #43 페이징바 수정
  MENDITTZO-Frontend/src/components/common/PagingBar.vue
Labels: 🎨 Style, 💻 Chore
